### ISSUE TITLE
Pins don't resize when zoomed in

### ISSUE THREAD

**Issue by isaacbw** [urbanarchive/qpl-name-explorer#35]
Priority: medium
Platform: web

![Image](https://user-images.githubusercontent.com/108014276/182191274-2b520999-78de-48e2-ac6a-9aacc90f6dbe.png)

![Image](https://user-images.githubusercontent.com/108014276/182191287-c2c2b365-ad3e-493f-8312-e5b0ac36741c.png)

**Comment by helmturner** [comment]
Closing this as not planned in light of the UA 2.0 Initiative
