### ISSUE TITLE
User uploads not highlighted on map

### ISSUE THREAD

**Issue by isaacbw** [urbanarchive/qpl-name-explorer#36]
Priority: low
Platform: web

Not sure if this is purposeful.

https://www.urbanarchive.org/sites/Q1LZhfxkuJN/yz7SAWX67gP
![Image](https://user-images.githubusercontent.com/108014276/182191477-cfd4b59c-cf36-4a22-b8ec-b6b903106eed.png)

**Comment by helmturner** [comment]
Closing this as not planned in light of the UA 2.0 initiative, but it poses interesting questions about how content discovery should differ between partner content and user content.
