### ISSUE TITLE
For admin users, when clicking "become anonymous," you get logged out.

### ISSUE THREAD

**Issue by isaacbw** [urbanarchive/qpl-name-explorer#43]
Priority: low
Platform: web

https://airtable.com/invite/l?inviteId=inv161RoSNx2bXqIu&inviteToken=e70184d153ae5c2b40344e482d1b5061c42009a89bc0d7c6b6a7109921fe9211&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts

Last item

**Comment by helmturner** [comment]
Well, technically, logging out *does* achieve the result of showing what the site would look like to an anonymous (not logged in) user.   I agree it's not a very well thought-out implementation, though, as you would expect to be able to restore your auth session *without* logging back in... but 🤷 . I'm closing this as 'not planned' in light of the UA 2.0 initiative.
